export enum TableNames {
  API_TOKENS_TABLE = "api_token",
  PROFILES_TABLE = "profile",
  USED_PLAN_COUNTER = "used_plan_counter",
  STORE = "store",
  STORE_ACCOUNTS = "store_account",
  STORE_ITEMS = "store_item",
  STORE_ITEM_OPTIONS = "store_item_option",
  STORE_ITEM_CHILD_OPTIONS = "store_item_child_option",
  STORE_POSITIONS = "store_position",
  DISCOUNTS = "store_discount",
  STORE_ORDERS = "store_order",
  STORE_ORDER_DETAILS = "store_order_detail",
  STORE_ITEMS_TYPES = "store_item_type",
  ADDRESS = "address",
  STORE_REPORT = "store_report",
  USER_SUBSCRIPTION = "user_subscription",
  STORE_USERS_SHIFT_PLAN = 'store_staff_shift_plan',
  STORE_SETTINGS = 'store_setting',
  MESSAGE_WISHES = 'hiu_wedding_wishes'
}
